import {
  BarChart3,
  BellRing,
  Bug,
  Building2,
  ClipboardList,
  ContactRound,
  FolderKanban,
  Globe,
  LayoutDashboard,
  ListTodo,
  Inbox,
  Megaphone,
  Network,
  PoundSterling,
  Puzzle,
  ShieldCheck,
  Users,
  Workflow,
} from 'lucide-react';

export const NAV_ITEMS = [
  { path: '/', label: 'Overview', icon: LayoutDashboard },
  { path: '/projects', label: 'Projects', icon: FolderKanban },
  { path: '/portfolio', label: 'Portfolio Register', icon: Building2 },
  { path: '/operations', label: 'Team & Operations', icon: Users },
  { path: '/work-board', label: 'Operations Board', icon: Workflow },
  { path: '/actions', label: 'Action Centre', icon: BellRing },
  { path: '/case-desk', label: 'Cases & Approvals', icon: Inbox },
  { path: '/crm', label: 'Clients & CRM', icon: ContactRound },
  { path: '/compliance', label: 'Compliance', icon: ShieldCheck },
  { path: '/partners', label: 'Third Parties', icon: Network },
  { path: '/marketing', label: 'Marketing & Sales', icon: Megaphone },
  { path: '/tasks', label: 'Tasks', icon: ListTodo },
  { path: '/costs', label: 'Costs', icon: PoundSterling },
  { path: '/infra', label: 'Domains & Infra', icon: Globe },
  { path: '/integrations', label: 'Integrations', icon: Puzzle },
  { path: '/checklists', label: 'Checklists', icon: ClipboardList },
  { path: '/qa', label: 'QA & Testing', icon: Bug },
  { path: '/users', label: 'Users & Roles', icon: Users },
  { path: '/reports', label: 'Reports', icon: BarChart3 },
] as const;
