import { FormEvent, useMemo, useState } from 'react';
import { AlertTriangle, CalendarClock, CheckCircle2, Plus, Search, ShieldCheck } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { supabase } from '@/integrations/supabase/client';
import { useProjects } from '@/hooks/useProjectData';
import { useComplianceRegister, useCrmAccountsFull, useOperationsPermission } from '@/hooks/useOperationsWorkspace';
import { cn } from '@/lib/utils';

const statuses = ['not_started', 'in_progress', 'waiting_external', 'review', 'approved', 'complete', 'blocked'];
const riskStyle: Record<string, string> = { low: 'text-muted-foreground', medium: 'text-blue-400', high: 'text-amber-400', critical: 'text-red-400' };

export default function Compliance() {
  const { data: items = [], isLoading, error } = useComplianceRegister();
  const { data: projects = [] } = useProjects();
  const { data: accounts = [] } = useCrmAccountsFull();
  const { data: permission } = useOperationsPermission();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const [territory, setTerritory] = useState('All');
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ requirement: '', category: 'Product compliance', territory: 'UK', risk_level: 'medium', project_id: '', account_id: '', entity_name: '', authority: '', due_date: '', renewal_date: '', external_adviser: '', legal_basis_or_scope: '' });
  const filtered = useMemo(() => items.filter((item) => (territory === 'All' || item.territory === territory) && `${item.requirement} ${item.category} ${item.authority} ${item.projects?.name} ${item.crm_accounts?.name}`.toLowerCase().includes(search.toLowerCase())), [items, search, territory]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['compliance-register'] });
  const create = async (event: FormEvent) => { event.preventDefault(); if (!form.project_id && !form.account_id && !form.entity_name) return toast.error('Choose a project, client or entity'); const { error: insertError } = await supabase.from('compliance_register').insert({ ...form, project_id: form.project_id || null, account_id: form.account_id || null, entity_name: form.entity_name || null, authority: form.authority || null, due_date: form.due_date || null, renewal_date: form.renewal_date || null, external_adviser: form.external_adviser || null, legal_basis_or_scope: form.legal_basis_or_scope || null }); if (insertError) return toast.error(insertError.message); refresh(); setOpen(false); toast.success('Compliance item created'); };
  const updateStatus = async (id: string, status: string) => { const { error: updateError } = await supabase.from('compliance_register').update({ status }).eq('id', id); if (updateError) return toast.error(updateError.message); refresh(); };
  const today = new Date().toISOString().slice(0, 10);
  const overdue = items.filter((item) => item.due_date && item.due_date < today && !['complete', 'approved'].includes(item.status)).length;

  if (isLoading) return <div className="min-h-[60vh] flex items-center justify-center text-sm text-muted-foreground">Loading…</div>;
  if (error) return <div className="text-sm text-destructive">Compliance register could not load: {error.message}</div>;
  return <div className="space-y-6 max-w-7xl">
    <div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Controlled register</p><h1 className="text-2xl font-bold tracking-tight mt-1">Compliance and statutory work</h1><p className="text-sm text-muted-foreground mt-1">Portfolio, B2B customer, company and authority requirements with maker-checker evidence.</p></div>{permission?.canManage && <Button onClick={() => setOpen(true)}><Plus size={14} className="mr-1" />Add requirement</Button>}</div>
    <div className="grid gap-3 sm:grid-cols-4">{[{ label: 'Open requirements', value: items.filter((i) => !['complete', 'approved'].includes(i.status)).length, icon: ShieldCheck }, { label: 'In review', value: items.filter((i) => i.status === 'review').length, icon: Search }, { label: 'Approved / complete', value: items.filter((i) => ['complete', 'approved'].includes(i.status)).length, icon: CheckCircle2 }, { label: 'Overdue', value: overdue, icon: AlertTriangle }].map(({ label, value, icon: Icon }) => <div key={label} className="glass-card rounded-xl p-4"><Icon size={17} className={label === 'Overdue' && value ? 'text-destructive' : 'text-primary'} /><div className="text-2xl font-bold mt-3">{value}</div><div className="text-xs text-muted-foreground">{label}</div></div>)}</div>
    <div className="flex gap-3 flex-wrap"><label className="flex items-center gap-2 rounded-lg border border-border/50 bg-muted/20 px-3 py-2 flex-1 max-w-sm"><Search size={14} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search requirement, project or authority" className="w-full bg-transparent text-sm outline-none" /></label><div className="flex gap-1 p-1 rounded-lg border border-border/50 bg-muted/20">{['All', 'UK', 'DE', 'INT', 'GROUP'].map((item) => <button key={item} onClick={() => setTerritory(item)} className={cn('px-3 py-1 rounded text-xs', territory === item ? 'bg-background shadow-sm' : 'text-muted-foreground')}>{item}</button>)}</div></div>
    <div className="glass-card rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-border/50">{['Requirement', 'Subject', 'Risk', 'Status', 'Due / renewal', 'Reviewer'].map((heading) => <th key={heading} className="text-left text-xs uppercase tracking-wider text-muted-foreground px-4 py-3">{heading}</th>)}</tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-b border-border/30 last:border-0"><td className="px-4 py-3"><div className="text-sm font-medium">{item.requirement}</div><div className="text-[10px] text-muted-foreground">{item.category} · {item.authority ?? 'Internal control'} · {item.territory}</div></td><td className="px-4 py-3 text-xs">{item.projects?.name ?? item.crm_accounts?.name ?? item.entity_name}</td><td className={cn('px-4 py-3 text-xs font-semibold capitalize', riskStyle[item.risk_level])}>{item.risk_level}</td><td className="px-4 py-3">{permission?.canManage ? <select value={item.status} onChange={(e) => updateStatus(item.id, e.target.value)} className="rounded border border-border bg-background px-2 py-1 text-xs">{statuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select> : <span className="text-xs">{item.status.replace('_', ' ')}</span>}</td><td className="px-4 py-3 text-xs text-muted-foreground"><div className="flex items-center gap-1"><CalendarClock size={12} />{item.due_date ?? 'No due date'}</div>{item.renewal_date && <div>Renews {item.renewal_date}</div>}</td><td className="px-4 py-3 text-xs text-muted-foreground">{item.external_adviser ?? 'Internal reviewer not assigned'}</td></tr>)}{!filtered.length && <tr><td colSpan={6} className="text-center py-12 text-sm text-muted-foreground">No compliance requirements match this view</td></tr>}</tbody></table></div></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Add compliance requirement</DialogTitle></DialogHeader><form onSubmit={create} className="space-y-3"><Input required value={form.requirement} onChange={(e) => setForm({ ...form, requirement: e.target.value })} placeholder="Requirement or filing" /><div className="grid sm:grid-cols-3 gap-2"><Input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Category" /><select value={form.territory} onChange={(e) => setForm({ ...form, territory: e.target.value })} className="rounded-md border border-input bg-background px-3 text-sm"><option>UK</option><option>DE</option><option>INT</option><option>GROUP</option></select><select value={form.risk_level} onChange={(e) => setForm({ ...form, risk_level: e.target.value })} className="rounded-md border border-input bg-background px-3 text-sm"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></div><div className="grid sm:grid-cols-2 gap-2"><select value={form.project_id} onChange={(e) => setForm({ ...form, project_id: e.target.value, account_id: '', entity_name: '' })} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choose project (optional)</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={form.account_id} onChange={(e) => setForm({ ...form, account_id: e.target.value, project_id: '', entity_name: '' })} className="rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choose client (optional)</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></div><Input value={form.entity_name} onChange={(e) => setForm({ ...form, entity_name: e.target.value, project_id: '', account_id: '' })} placeholder="Or legal entity name" /><div className="grid sm:grid-cols-2 gap-2"><Input value={form.authority} onChange={(e) => setForm({ ...form, authority: e.target.value })} placeholder="Authority / regulator" /><Input value={form.external_adviser} onChange={(e) => setForm({ ...form, external_adviser: e.target.value })} placeholder="Qualified adviser / reviewer" /></div><Input value={form.legal_basis_or_scope} onChange={(e) => setForm({ ...form, legal_basis_or_scope: e.target.value })} placeholder="Scope, licence or legal basis" /><div className="grid grid-cols-2 gap-2"><label className="text-xs text-muted-foreground">Due<Input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></label><label className="text-xs text-muted-foreground">Renewal<Input type="date" value={form.renewal_date} onChange={(e) => setForm({ ...form, renewal_date: e.target.value })} /></label></div><Button type="submit" className="w-full">Create requirement</Button></form></DialogContent></Dialog>
  </div>;
}

