import { FormEvent, useMemo, useState } from 'react';
import { Building2, CalendarClock, CheckSquare2, Plus, Search } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { supabase } from '@/integrations/supabase/client';
import { useProjects } from '@/hooks/useProjectData';
import { useOperationsPermission, useThirdPartyRegister } from '@/hooks/useOperationsWorkspace';
import { cn } from '@/lib/utils';

const statuses = ['not_started', 'contacted', 'application', 'waiting_external', 'testing', 'approved', 'live', 'blocked', 'closed'];

export default function Partners() {
  const { data: items = [], isLoading, error } = useThirdPartyRegister();
  const { data: projects = [] } = useProjects();
  const { data: permission } = useOperationsPermission();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const [territory, setTerritory] = useState('All');
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ organisation: '', category: 'Provider', territory: 'GROUP', required_deliverable: '', project_id: '', external_owner_name: '', status: 'not_started', due_date: '', renewal_date: '', dependency: '', qualification_required: '', can_be_brought_in_house: true });
  const filtered = useMemo(() => items.filter((item) => (territory === 'All' || item.territory === territory || item.territory === 'GROUP') && `${item.organisation} ${item.category} ${item.required_deliverable} ${item.projects?.name}`.toLowerCase().includes(search.toLowerCase())), [items, search, territory]);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['third-party-register'] });
  const create = async (event: FormEvent) => { event.preventDefault(); const { error: insertError } = await supabase.from('third_party_actions').insert({ ...form, project_id: form.project_id || null, external_owner_name: form.external_owner_name || null, due_date: form.due_date || null, renewal_date: form.renewal_date || null, dependency: form.dependency || null, qualification_required: form.qualification_required || null }); if (insertError) return toast.error(insertError.message); refresh(); setOpen(false); toast.success('Third-party action created'); };
  const updateStatus = async (id: string, status: string) => { const { error: updateError } = await supabase.from('third_party_actions').update({ status }).eq('id', id); if (updateError) return toast.error(updateError.message); refresh(); };

  if (isLoading) return <div className="min-h-[60vh] flex items-center justify-center text-sm text-muted-foreground">Loading…</div>;
  if (error) return <div className="text-sm text-destructive">Third-party register could not load: {error.message}</div>;
  return <div className="space-y-6 max-w-7xl">
    <div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">External dependency register</p><h1 className="text-2xl font-bold tracking-tight mt-1">Third parties and qualified advisers</h1><p className="text-sm text-muted-foreground mt-1 max-w-3xl">Provider deliverables, applications, evidence, dependencies, renewals and escalation—with the option to move qualified work in-house later.</p></div>{permission?.canManage && <Button onClick={() => setOpen(true)}><Plus size={14} className="mr-1" />Add action</Button>}</div>
    <div className="grid gap-3 sm:grid-cols-4">{[{ label: 'Relationships', value: items.length }, { label: 'Waiting externally', value: items.filter((i) => i.status === 'waiting_external').length }, { label: 'Testing', value: items.filter((i) => i.status === 'testing').length }, { label: 'Approved / live', value: items.filter((i) => ['approved', 'live'].includes(i.status)).length }].map((card) => <div key={card.label} className="glass-card rounded-xl p-4"><div className="text-2xl font-bold">{card.value}</div><div className="text-xs text-muted-foreground">{card.label}</div></div>)}</div>
    <div className="flex gap-3 flex-wrap"><label className="flex items-center gap-2 rounded-lg border border-border/50 bg-muted/20 px-3 py-2 flex-1 max-w-sm"><Search size={14} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search provider or deliverable" className="w-full bg-transparent text-sm outline-none" /></label><div className="flex gap-1 p-1 rounded-lg border border-border/50 bg-muted/20">{['All', 'UK', 'DE', 'INT', 'GROUP'].map((item) => <button key={item} onClick={() => setTerritory(item)} className={cn('px-3 py-1 rounded text-xs', territory === item ? 'bg-background shadow-sm' : 'text-muted-foreground')}>{item}</button>)}</div></div>
    <div className="grid gap-3 lg:grid-cols-2">{filtered.map((item) => <article key={item.id} className="glass-card rounded-xl p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><Building2 size={18} className="text-primary mt-0.5" /><div><h2 className="font-semibold">{item.organisation}</h2><div className="text-xs text-muted-foreground">{item.category} · {item.territory}{item.projects ? ` · ${item.projects.name}` : ''}</div></div></div>{permission?.canManage ? <select value={item.status} onChange={(e) => updateStatus(item.id, e.target.value)} className="rounded border border-border bg-background px-2 py-1 text-xs">{statuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select> : <span className="text-xs">{item.status}</span>}</div><div className="mt-4 space-y-3 text-xs"><div><div className="font-medium mb-1">Must deliver</div><p className="text-muted-foreground">{item.required_deliverable}</p></div>{item.external_owner_name && <div><div className="font-medium">External owner</div><p className="text-muted-foreground">{item.external_owner_name}</p></div>}<div className="grid grid-cols-2 gap-3"><div><div className="font-medium flex items-center gap-1"><CalendarClock size={12} />Due</div><p className="text-muted-foreground">{item.due_date ?? 'Not set'}</p></div><div><div className="font-medium">Renewal</div><p className="text-muted-foreground">{item.renewal_date ?? 'Not set'}</p></div></div>{item.dependency && <div><div className="font-medium">Dependency / blocker</div><p className="text-muted-foreground">{item.dependency}</p></div>}{item.qualification_required && <div><div className="font-medium flex gap-1 items-center"><CheckSquare2 size={12} />Qualification required</div><p className="text-muted-foreground">{item.qualification_required}</p></div>}<div className="text-[10px] text-primary">{item.can_be_brought_in_house ? 'Can be reassigned to a suitably qualified employee' : 'External provider relationship required'}</div></div></article>)}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Add third-party action</DialogTitle></DialogHeader><form onSubmit={create} className="space-y-3"><Input required value={form.organisation} onChange={(e) => setForm({ ...form, organisation: e.target.value })} placeholder="Provider, authority or adviser" /><div className="grid sm:grid-cols-3 gap-2"><Input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Category" /><select value={form.territory} onChange={(e) => setForm({ ...form, territory: e.target.value })} className="rounded-md border border-input bg-background px-3 text-sm"><option>UK</option><option>DE</option><option>INT</option><option>GROUP</option></select><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="rounded-md border border-input bg-background px-3 text-sm">{statuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select></div><select value={form.project_id} onChange={(e) => setForm({ ...form, project_id: e.target.value })} className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Group / no project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><Input required value={form.required_deliverable} onChange={(e) => setForm({ ...form, required_deliverable: e.target.value })} placeholder="What the third party must deliver" /><Input value={form.external_owner_name} onChange={(e) => setForm({ ...form, external_owner_name: e.target.value })} placeholder="Named external contact" /><Input value={form.dependency} onChange={(e) => setForm({ ...form, dependency: e.target.value })} placeholder="Dependency or blocker" /><Input value={form.qualification_required} onChange={(e) => setForm({ ...form, qualification_required: e.target.value })} placeholder="Qualification / authorisation required" /><div className="grid grid-cols-2 gap-2"><label className="text-xs text-muted-foreground">Due<Input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></label><label className="text-xs text-muted-foreground">Renewal<Input type="date" value={form.renewal_date} onChange={(e) => setForm({ ...form, renewal_date: e.target.value })} /></label></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.can_be_brought_in_house} onChange={(e) => setForm({ ...form, can_be_brought_in_house: e.target.checked })} />Can later be assigned to a qualified employee</label><Button type="submit" className="w-full">Create third-party action</Button></form></DialogContent></Dialog>
  </div>;
}

