-- Intentionally empty.
--
-- This generated migration duplicated
-- 20260906001000_next_phase_crm_workspaces.sql byte-for-byte. Keeping this
-- timestamp as a no-op preserves migration history for environments that have
-- already recorded it while preventing duplicate policy, trigger and index
-- creation on a fresh deployment.
